Repository overture-stack/SONG, pull requests merged in 2019-02, with the labels that each got.

#389 Adds support for .tgz filetypes as part of analysis.
  song-core/src/main/java/bio/overture/song/core/model/enums/FileTypes.java
  song-server/src/main/resources/schema.sql
  song-server/src/main/resources/schemas/sequencingRead.json
  song-server/src/main/resources/schemas/variantCall.json
  song-server/src/test/java/bio/overture/song/server/constants/ConstantsTest.java
  song-server/src/test/java/bio/overture/song/server/service/FileServiceTest.java
  song-server/src/test/java/bio/overture/song/server/validation/ValidationServiceTest.java
  song-server/src/test/resources/documents/validation/sequencingReadWithArchive.json
Labels: review

#391 fix: Using new exclude-urls param for avoid deadlock
  song-server/src/main/java/bio/overture/song/server/service/StorageService.java
  song-server/src/test/java/bio/overture/song/server/service/StorageServiceTest.java
Labels: bug, review

#392 ci: Updates song-docker to score 1.6.1 and song 1.4.1
  song-docker/client/Dockerfile
  song-docker/db/Dockerfile
  song-docker/server/Dockerfile
  song-docker/storage-client/Dockerfile
  song-docker/storage-server/Dockerfile
Labels: review

#396 Update docker.rst
  song-docs/source/docker.rst
  song-docs/source/song-docker-service-architecture.svg
Labels: review

#399 Update the song docs with the correct artifact link.
  song-docs/source/server.rst
Labels: review

#398 replace spring @Transactional with javax @Transactional
  pom.xml
  song-server/pom.xml
  song-server/src/main/java/bio/overture/song/server/controller/FileController.java
  song-server/src/main/java/bio/overture/song/server/repository/search/SearchRepository.java
  song-server/src/main/java/bio/overture/song/server/service/AnalysisService.java
  song-server/src/main/java/bio/overture/song/server/service/DonorService.java
  song-server/src/main/java/bio/overture/song/server/service/FileModificationService.java
  song-server/src/main/java/bio/overture/song/server/service/FileService.java
  song-server/src/main/java/bio/overture/song/server/service/SampleService.java
  song-server/src/main/java/bio/overture/song/server/service/SpecimenService.java
  song-server/src/main/java/bio/overture/song/server/service/StudyService.java
  song-server/src/main/java/bio/overture/song/server/service/UploadService.java
  song-server/src/test/java/bio/overture/song/server/service/DonorServiceTest.java
  song-server/src/test/java/bio/overture/song/server/service/ExportServiceTest.java
  song-server/src/test/java/bio/overture/song/server/service/FileModificationServiceTest.java
  song-server/src/test/java/bio/overture/song/server/service/FileServiceTest.java
  song-server/src/test/java/bio/overture/song/server/service/PublishAnalysisTest.java
  song-server/src/test/java/bio/overture/song/server/service/SampleServiceTest.java
  song-server/src/test/java/bio/overture/song/server/service/SpecimenServiceTest.java
  song-server/src/test/java/bio/overture/song/server/service/UploadServiceTest.java
Labels: SP:1, review
